### ISSUE TITLE
F10 & F20: Registrierung

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#26]
##  Registrierung (__F10 & F20__)
Ziel ist es den neuen Benutzer mit Vorname, Nachname, E-Mail-Adresse und Passwort zu registrieren.
______________________________________________
## Abhängigkeiten
- UI für das Registrieren
- Registrierung ist Voraussetzung für Login (__#27__)
______________________________________________  
## Technische Abhängigkeiten
- Vorname, Nachname, E-Mail-Adresse und Passwort-Hash müssen in die Datenhaltung übernommen werden.
______________________________________________
## Funktionsbeschreibung
- Der Benutzer gelangt auf das UI für die Registrierung.
- Der Benutzer gibt für die Registrierung Vorname, Nachname, E-Mail-Adresse und Passwort ein.
- Der Server-Admin kann in der Benutzerverwaltung beliebige Spieler zu MUD-Mastern erklären.
- Das Hinzufügen des Vor- und Nachnamen dient der Übersichtlichkeit für den Admin.
______________________________________________
### Server
- Überprüfen ob E-Mail-Adresse bereits in Datenhaltung vorhanden (E-Mail muss unique sein)
- Überführen von Vorname, Nachname, E-Mail-Adresse und des Passwortes in die Datenhaltung.
______________________________________________
### Client
- Ein Wechsel zwischen Login-UI (__#27__) und Registrierung-UI ist jederzeit möglich
- Wenn der Benutzer noch nicht registriert ist, kann er sich auf dieser UI registrieren. 
__________________________________________
## Designvorschlag
![DrawioRegistrierungV2](https://user-images.githubusercontent.com/48104013/79111514-efc05f00-7d7c-11ea-9ce7-9cd0cb88f3ae.png)
__________________________________________
## Offene Fragen
- [x] __Kann der User bei der Registrierung den Wunsch per Häkchen äußern, dass er zu einem MUD-Master ernannt werden möchte?__
 Der User kann diese zusätzliche Benutzerrolle bereits bei der Registrierung anfordern. Er hat aber auch zu einem späteren Zeitpunkt die Möglichkeit die Benutzerrolle anzufordern.
- [x] __Kann man sich mehrmals mit der gleichen E-Mail-Adresse registrieren?__
 Nein. Die E-Mail-Adresse muss in der Datenhaltung unique sein.

**Comment by KotschM** [comment]
Kann der User bei der Registrierung den Wunsch per Häkchen äußern, dass er zu einem MUD-Master ernannt werden möchte?

**Comment by KotschM** [comment]
Kann man sich mehrmals mit der gleichen E-Mail-Adresse registrieren?

**Comment by langmario** [comment]
Email  dient als Identifier für die Konten und muss daher unique sein, also sollte man sich nicht mehrfach  mit der selben Email registrieren können

**Comment by maSchoeller** [comment]
> 
> 
> Email dient als Identifier für die Konten und muss daher unique sein, also sollte man sich nicht mehrfach mit der selben Email registrieren können

Ja, die Email sollte unique sein. Trotzdem wäre es nicht schlecht wenn wir die Email später in der Datenbank nicht als primary Key nehmen, dadurch haben wir die möglichkeit die Email im nachhinein leicht zu ändern.

>
>
>Kann der User bei der Registrierung den Wunsch per Häkchen äußern, dass er zu einem MUD-Master ernannt werden möchte?

Kann man machen, wir sollten aber trotzdem auf jeden Fall eine Möglichkeit bieten das Später noch anzufordern, von dem her würde ich die Porzesse "Registieren" und "Mud Master anfragen" aufteilen,  dem Benutzer können wir das ja durchaus so darstellen als ob das ein Porzess wäre.

**Comment by maSchoeller** [comment]
__Was haltet ihr davon, wenn wir noch die Angabe von einem Benutzernamen aufnehmen?__
Dadurch sieht ein MUD Master/Admin nicht (nur) die Email sondern auch ein Benutzername, bei Verwaltungsbearbeitungen.

**Comment by KotschM** [comment]
> **Was haltet ihr davon, wenn wir noch die Angabe von einem Benutzernamen aufnehmen?**
> Dadurch sieht ein MUD Master/Admin nicht (nur) die Email sondern auch ein Benutzername, bei Verwaltungsbearbeitungen.

Dann gilt der Benutzername dann nur innerhalb der Benutzerverwaltung. Dann muss jeder Spieler für jedes MUD einen Benutzernamen anlegen.

**Comment by KotschM** [comment]
> > Email dient als Identifier für die Konten und muss daher unique sein, also sollte man sich nicht mehrfach mit der selben Email registrieren können
> 
> Ja, die Email sollte unique sein. Trotzdem wäre es nicht schlecht wenn wir die Email später in der Datenbank nicht als primary Key nehmen, dadurch haben wir die Möglichkeit die Email im nachhinein leicht zu ändern.
> 
> > Kann der User bei der Registrierung den Wunsch per Häkchen äußern, dass er zu einem MUD-Master ernannt werden möchte?
> 
> Kann man machen, wir sollten aber trotzdem auf jeden Fall eine Möglichkeit bieten, das später noch anzufordern.
> Ich würde die Registierung in die Porzesse "Registieren" und "Mud Master anfragen" aufteilen, dem Benutzer können wir das ja durchaus so darstellen als ob das ein Porzess wäre, die bei der Anmeldung nacheinander ablaufen (können).

**Comment by maSchoeller** [comment]
> 
> 
> > **Was haltet ihr davon, wenn wir noch die Angabe von einem Benutzernamen aufnehmen?**
> > Dadurch sieht ein MUD Master/Admin nicht (nur) die Email sondern auch ein Benutzername, bei Verwaltungsbearbeitungen.
> 
> Dann gilt der Benutzername dann nur innerhalb der Benutzerverwaltung. Dann muss jeder Spieler für jedes MUD einen Benutzernamen anlegen.

Das wäre der Gedanke.

Pro Charakter in den MUD Spielen gibt es noch einen extra "Chrakternamen" oder?

**Comment by langmario** [comment]
> **Was haltet ihr davon, wenn wir noch die Angabe von einem Benutzernamen aufnehmen?**
> Dadurch sieht ein MUD Master/Admin nicht (nur) die Email sondern auch ein Benutzername, bei Verwaltungsbearbeitungen.

Die Frage ist, was so ein globaler Nutzername für einen Mehrwert bringt, wenn in den einzelnen MUDs ein separater Name gewählt werden muss.
Ich würde bei der Registrierung klassisch Vor- und Nachname, Email und Passwort verlangen

**Comment by avh5711** [comment]
> Email dient als Identifier für die Konten und muss daher unique sein, also sollte man sich nicht mehrfach mit der selben Email registrieren können

Korrekt, sehe ich auch so. Bzgl. extra Benutzernamen habe ich keine Präferenz. Machen Sie es jedoch für sich nicht zu schwierig. Es ist nicht zentral für das Projekt (gesprochen als Betreuer)

**Comment by KotschM** [comment]
Daten für die Registrierung sind "Vorname", "Nachname", "E-Mail-Adresse" und Passwort.
