### ISSUE TITLE
F40 & F270: MUD-Übersicht

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#28]
## MUD-Übersicht (__F40 & F270__)
Es gibt eine Übersicht über die zur Verfügung stehenden MUDs.
___________________________________________
## Abhängigkeiten
- Registrierung und Login der User (__#26 & #27__ )
- Konfigurieren von MUDs
___________________________________________
## Technische Abhängigkeiten
- Es werden nur die MUDs angezeigt, welche öffentlich sind oder für den jeweiligen Spieler zur Verfügung stehen.
___________________________________________
## Funktionsbeschreibung
- Aus zwei Bereichen können MUDs ausgewählt werden. Die öffentlichen MUDs (für alle Spieler) und die privaten MUDs (zugänglich nur für bestimmte Spieler).
- Nach dem Auswählen eines MUDs kann entweder ein bestehender Spielstand oder ein neuer Spielstand ausgewählt werden. (Siehe Designvorschlag)
___________________________________________
### Server
- MUDs und Spielstände müssen in der Datenhaltung berücksichtigt werden.
___________________________________________
### Client
- Je nach Rolle des Benutzers müssen Tabs angezeigt werden oder eben nicht.
___________________________________________
## Designvorschlag
![DrawioMUDAuswaehlenV2](https://user-images.githubusercontent.com/48104013/79114276-28633700-7d83-11ea-9bf6-fdb8524e5040.png)
___________________________________________
## Offene Fragen
- [x] __Sollen alle privaten MUDs angezeigt werden? MUDs, für welche der Spieler keine Berechtigung hat, werden dann mit einem Schloss-Symbol markiert.__
 Ja so soll es sein.
- [x] __Soll es die Möglichkeit geben eine Anfrage für gesperrte private MUDs zu stellen?__
 Ja so soll es sein.

**Comment by benitadietrich** [comment]
Also grundsätzlich fände ich diese Möglichkeiten sehr gut. Also sowohl, dass private MUDs mit einem Schlosssymbol markiert sind, als auch das Anfragen gestellt werden können. Wäre dies allerdings nur zusätzlich viel Aufwand würde ich dies weglassen.
