### ISSUE TITLE
Mein Konto - Übersicht

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#33]
## Mein Konto - Übersicht
Der Benutzer hat die Möglichkeit verschieden Daten seines Kontos einzusehen und zu ändern.
_______________________________________
## Abhängigkeiten
- /
_______________________________________
## Technische Abhängigkeiten
- Datenhaltung muss stets valide sein.
_______________________________________
## Funktionsbeschreibung
- __Einsehen von:__
  - Vorname, Nachname
  - E-Mail-Adresse
- __Ändern von:__
  - Vorname, Nachname
  - Passwort
_______________________________________
### Server
- Validierung der Eingaben
_______________________________________
### Client
- Validierung der Eingaben
_______________________________________
## Designvorschlag
Hier kommt ein Bild rein
_______________________________________
## Offene Fragen
- [x] __Soll in die "Mein Konto"-Ansicht auch eine Auflistung aller Charaktere der verschiedenen MUDs angezeigt werden oder soll solch eine Auflistung lediglich in der MUD-Übersicht (#28) angezeigt werden?__
 Eine Auflistung der Spielstände der verschiedenen MUDs findet nicht in der "Mein Konto"-Ansicht statt.
- [x] __Soll die Möglichkeit bestehen den Vor- und Nachnamen zu ändern? Vor- und Nachnamen werden für die Benutzerverwaltung des Admins benötigt.__
 Ja die Vor- und Nachnamen können geändert werden.
- [x] __Soll das Löschen von einzelnen Spielständen (Instanzen von Charakteren in einem MUD) ermöglicht werden?__
 Das Löschen einzelner Spielstände hat auf der "Mein Konto"-Ansicht nichts verloren.

**Comment by langmario** [comment]
@pafinkbeiner  und ich setzen uns heute Nachmittag mal an die Wireframes und klären dass aus UI Sicht ab
Alles, was mit den Spielständen der einzelnen MUDs zu tun hat, hat auf der Kontoseite eigentlich nichts verloren
