### ISSUE TITLE
F80,F90,F100: Areas & Rooms, Serverseitig

### ISSUE THREAD

**Issue by maSchoeller** [MUDHub/MUDhub#35]
## Ziel des Features
Der Charakter soll in einen MudGame später von Raum zu Raum wandern können und zusätzlich die Areas wechseln können.

## Abhängigkeiten
- Charakterverwaltung(Issue __TODO__)
  
## Technische Abhängigkeiten
- Änderungen an der Datenbank
- Änderungen am Server, später auch am Client

## Communikation
__Die Schnittstellen müssen im zweiten Schritt noch definiert werden!__
### Api Schnittstelle
__TODO__
### SignalR
__TODO__

### Statisches Modell
![RoomsManagment](https://user-images.githubusercontent.com/56505280/79222664-40f15100-7e58-11ea-98a3-e7952d63ef20.png)
- Alle Modellobjekte bekommen einen Id(Guid).
-  Die `RoomConnections` stellen die Verbindung zwischen den Räumen dar, so können dort später gegenenfalls Bedingungen angeknüpft werden. 
  _z.B. Ein Charakter kann einen andern Raum nur betreten wenn er den Gegenstand Schlüssel besitzt oder der Raum kann nur im laufe einer Quest betreten werden._
- Die `RoomsInteractions` stellen Interaktionen dar die im Raum möglich sind, _z.B. kann ein Charakter einen Apfel im Wald aufsammeln oder später könnten dort NPC\/Mobs gespeichert werden._
- Der `DbContext` ist die Datenbankschnittstelle
- Der `RoomsManager` ist eine Abstraktionsschicht zwischen dem `DbContext` und den Schnittstellen zum Client und  anderen Services, Ziel ist eine bearbeitung "am offenen Herzen" zu verhindern.
- Der `NavigationService` kapselt die Funktionalität vom Wandern  der Charakter in den Räumen und Überprüft ob das Wechseln der Räume möglich ist.
- Die `ConnectionDirection` ist ein Enum, das die Himmelsrichtung angibt oder als Portal markiert ist.
  _Es wird dir Richtung von `Room1` zu `Room2` angegeben._
### Dynamisches Modell
__TODO__
## Offene Fragen
- [x] Die `RoomConnection` kann momentan das folgende Szenario __nicht__ abbilden: Ein Charakter kann von Räumen __A --> B__ wandern, aber der Weg von __B --> A__ ist gesperrt, _z.B. beim Springen von einer Klippe_
  __Es ist auch nicht geplant dies zu Implementieren.__
- [x] Wie gehen wir mit dem Aufsammeln von Gegenständen um? Soll ein Charakter nach betreten des Raumes den Gegenstand immer wieder aufsammeln können?
  __Alternativen__
  1. Der Charakter kann bei jedem Betreten den Gegenstand neu aufsammeln.
  2. Es wird pro Charakter gespeichert ob er den Gegenstand bereits gesammelt hat.
 __Ergebnis__
 #40 
## Amerkungen
- Der `UserManager` und `NavigationService` werden durch Interfaces noch abstrahiert.
- Ein großes Thema ist auch, wie gehen wir mit Informationen um, die erst zur __Laufzeit__ generiert werden, wo werden diese abgespeichert? 
  _Beispielsweise, die aktuelle Raumposition eines Charakters oder auch das Inventar eines Charakters, so dass dies in möglichst kleinen Abständen persisitiert wird._

**Comment by benitadietrich** [comment]
Also ich fände zur zweiten Frage Variante 2 besser, da ansonsten unlimitiert Gegenstände (oder Geld) gesammelt werden kann.

**Comment by maSchoeller** [comment]
Naja, keine Frage es wäre auf jeden Fall besser, es ist nur leider nicht so einfach umzusetzten, weil wir dann speichern müssen, ob dieser Gegenstand bereits aufgesammelt wurde und das eig. pro Charakter. Es ergeben sich dadurch viele neue Fragen:
- Soll der Gegenstand einmal Gobal über alle Charakter hinweg da sein, bedeutet sobald dieser aufgehoben wurde können ihn andere Charakter nicht mehr aufheben. __(das würde ich nicht machen)__
- Soll es Gegenstände geben, die z.B. nach einer Zeitspanne x wieder "spawnen". __(würde ich auch erstmal weglassen)__
  _Beispielsweise, Äpfel in einem Wald._
- Soll es Keygegenstände geben die ein Charakter nur einmal besitzten kann. __(Das wäre die Alternative)__
  _Beispielsweise ein Schlüssel._

Ich persönlich würde zu Variante 1 oben im Issue tendieren und damit das Farmen von Gegenständen hinnehmen. Ist aber durchaus durchaus eine schwierige Frage da aus meiner Sicht, das schon einen großen Mehrwert bieten würde, bei den Gegenständen.

Ich mach mir mal Gedanken und entwerfe die Tage einen Designvorschlag.
Was halten Sie davon @avh5711, zu was würden Sie tendieren?
