### ISSUE TITLE
Testkonzept

### ISSUE THREAD

**Issue by benitadietrich** [MUDHub/MUDhub#36]
### Komponententest
Werden im Rahmen von Unit-Tests mit den Tools XUnit für das .NET-Framework und Jasmine für Angular.

### Systemtests
- [x] **Frage 1: Wie wollen wir die Systemtests durchführen? Hierzu benötigen wir einheitliche Testdaten erstellen und diese Ablegen. Im Testkonzept muss hierzu genau dokumentiert werden wo diese herkommen und wie wir vorgehen. Soll hierfür im Projekt ein Ordner angelegt werden und die Daten dort abgelegt werden?**
 Systemtest werden manuell ausgeführt.

### Konzeptionelles
- [x] __Frage 2: Wie konkret lösen wir die Strukturierung der Testfiles. Lehnen wir uns hier an Maven an und es gibt einen separaten "test" Ordner oder wie habt ihr euch dies für den Server und Client vorgstellt? Nach Möglichkeiten sollten alle Komponententests einfach zu finden und gut strukturiert sein. Hierzu wurden bereits Testing Richtlinien im Wiki erstellt, die hier auch einfließen.__
 Clientseitig: https://github.com/MUDHub/MUDhub/issues/36#issuecomment-614272527
 Serverseitig: https://github.com/MUDHub/MUDhub/issues/36#issuecomment-614277520

### Organisatorisches
Siehe Testing Richtlinien

### Testautomatisierung
- __@maSchoeller hat bei der Review 1 Präsentation etwas darüber erwähnt. Könntest du dazu eventuell einen kleinen Abschnitt verfassen?__
 siehe https://github.com/MUDHub/MUDhub/issues/36#issuecomment-614281263

### Gliederung
1. Einführung (Zusammenfassung)

2. Testgegenstand
- Beschreibt was getestet wird und welche Umstände zu berücksichtigen sind (einzelne Komponenten, Unterprogramme, etc)
- Funktionalität in einem abgrenzbaren Teil einer Software

3. Zu testende Eigenschaften

4. Nicht zu testende Eigenschaften

- [x] **Frage 3: Welche Eigenschaften seht ihr konkret als essentiell an, sodass sie getestet werden müssen und welche eher nicht?**
  Nicht testen: Framework

5. Testansatz
- Teststrategie

6. Kriterien für Testende und -abbruch 

7. Testergebnisse

8. Zuständigkeiten

9. Erforderliche Voraussetzungen
- u.A Testumgebungen

10. Testplan

11. Risiken und Notfallplan

12. Genehmigung/Freigabe

Die obenstehende Gliederung ist aus der Norm IEEE 829 abgeleitet. Eine kurze Rückmeldung, ob das alles so passt oder weitere Anregungen und Vorschläge, sowie einige Antworten auf die obigen Fragen wären durchaus sehr hilfreich.

**Comment by langmario** [comment]
In Angular liegen die Testfiles jeweils im selben Ordner wie der Code der Komponente / des Services:

HomeComponent/home.component.html
HomeComponent/home.component.ts
HomeComponent/home.component.spec.ts <- **Testfile**

services/test.service.ts
services/test.service.spec.ts <- **Testfile**

**Comment by KotschM** [comment]
> In Angular liegen die Testfiles jeweils im selben Ordner wie der Code der Komponente / des Services:
> 
> HomeComponent/home.component.html
> HomeComponent/home.component.ts
> HomeComponent/home.component.spec.ts <- **Testfile**
> 
> services/test.service.ts
> services/test.service.spec.ts <- **Testfile**

Bezieht sich dieser Kommentar auf Frage 2 clientseitig? @langmario

**Comment by langmario** [comment]
> Bezieht sich dieser Kommentar auf Frage 2 clientseitig? @langmario

Jawohl

**Comment by KotschM** [comment]
> > Bezieht sich dieser Kommentar auf Frage 2 clientseitig? @langmario
> 
> Jawohl

Hab das eigentliche Issue dementsprechend aktualisiert :D

**Comment by maSchoeller** [comment]
Im Server Projekt ist das schon mal Testweise angelegt.
[Hier der Link](https://github.com/MUDHub/MUDhub/tree/develop/src/server)

- __MUDhub.Core.*__: Eine .Net Standard Klassenbibliothek
_Enthält die Businesslogik des Servers_
- __MUDhub.Core.Tests.*__: Ein xUnit Testprojekt, dass die Klassenbibliothek Unitestet
- __MUDhub.Server.*__: Der eigentliche ASPNET CORE (web) Server, Hostet die MUD Server und nutzt hierfür die Klassenbibliothek
- __MUDhub.Server.Tests.*__ _(optional)_: Das xUnit Testprojekt für den Server, kann die API Schnittstellen Unittesten.

Bei den Core Tests befinden wir uns vermutlich eher im bereich Unittests und bei den Server Tests sind es dann schon eher Komponententests, da hängt auch noch mehr dran und die sind auch schwieriger zu testen.

**Comment by maSchoeller** [comment]
>Testautomatisierung
>Frage 3: @maSchoeller hat bei der Review 1 Präsentation etwas darüber erwähnt. Könntest du dazu eventuell einen kleinen Abschnitt verfassen?

Die Tests werden, stand Heute, für den Serverteil bei jedem __Pull Request__ durchgeführt und nach dem durchführen wir ein Report mit __Code Coverage__ erstellt, also _"wie gut"_ der Quellcode durch das Testen abgedeckt ist. Wir können hier später noch ein "Quality Gate" rein machen, dass das Mergen nur dann zulässt, wenn die Code Coverage über eine Prozentzahl x beträgt. Momentan wird nur geschaut, ob die Tests fehlerfrei laufen, nur dann kann gemerged werden.

Sobald das Client Projekt da ist, können wir schauen wie wir das integieren, Serverseitig steht das.
