### ISSUE TITLE
F10, F20, F30, F260: Benutzerverwaltung

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#38]
## Feature Issues
- __#26 (Registrierung)__
- __#27 (Login)__ 
- __#30 (Benutzerverwaltung)__

### Statisches Modell

siehe: Server > Statisches Modell

#### Registrierung

![Registrierung](https://user-images.githubusercontent.com/47927947/79438860-61deb100-7fd4-11ea-8fa2-e88d5e5ca349.jpg)

### Api Schnittstelle ||TODO
Siehe #42 

### Statisches Modell
![Benutzerverwaltung](https://user-images.githubusercontent.com/48104013/79434427-a6ffe480-7fce-11ea-8588-de724a707bf6.png)

## Offene Fragen
- /

**Comment by maSchoeller** [comment]
`http://game.mudhub.de/api/auth/loadUser`
was bewirkt der Endpoint?
Und sollen wir bei der Schnittstelle evtl. einfach auf das Issue #42 verweisen, damit wir die Sachen nicht zweimal diskutieren?

**Comment by KotschM** [comment]
> `http://game.mudhub.de/api/auth/loadUser`
> was bewirkt der Endpoint?
> Und sollen wir bei der Schnittstelle evtl. einfach auf das Issue #42 verweisen, damit wir die Sachen nicht zweimal diskutieren?

Den Endpoint hatte ich aus einer TXT, welche vermutlich als Grundlage für #42 galt. Ich habe auf #42 verwiesen
