### ISSUE TITLE
Bilder Management auf dem Server

### ISSUE THREAD

**Issue by maSchoeller** [MUDHub/MUDhub#39]
# Beschreibung 
Wir habe Szenarien, bei denen serverseitig Bilder gespeichert werden müssen, so sollte ein Raum ein Bild besitzen. Dadurch, dass wir die Funktionalität "Bilder hinzufügen" sowieso bereitstellen ergeben sich viele andere Situationen, wo es evtl. auch Sinn macht, so z.B. :
- Bei Gegenständen
- Rassen und Klassen
- MOBs
.....

Die Frage ist jetzt, wie wir das technisch Umsetzten. Ich beschränke mich dabei auf das persistieren der Bilder und lasse jetzt mal außen vor, wie die auf den Server kommen, das ist eine Frage für sich, wobei dies eigentlich gut lösbar sein sollte.

Die alternativen zum Speichern sind:
1. Die Bilder werden in der SQL Datenbank mitgespeichert, das ist die einfachste Lösung jedoch auch die unschönste, da "große" Datenmengen wie Bilder nicht in einem SQL Server gespeichert werden sollten.
2. Ein Filestorage, auf dem lokalen Server, das wäre die nächst einfachere Version. Nachteil dabei, wenn der Server als Serverless Service _(wie er es momentan bei uns betrieben wird)_ betrieben wird verlieren wir alle Bilder, sobald der Server wieder runtergefahren ist. Das würde aber nur uns beim Betreiben betreffen und nicht die Abgabe selbst. Außerdem müssen wir eine Systematik festlegen wie die Bilder abgespeichert werden und dann später auch wieder gefunden werden können.
3. Ein Filestorage, irgendwo in der Cloud, z.B. Azure Blob Storage. Das wäre aber mit Abstand die aufwändigste Möglichkeit und es bleibt das Problem mit der Systematik zum abspeichern.

Ich persönlich würde zu Möglichkeit 2 Tendieren und es darauf ankommen lassen, ob die Bilder wirklich gelöscht werden, ganz sicher bin ich mir nämlich nicht, wenn wir den Service auf Windows hosten. Wie seht ihr das?

## Offene Fragen
- [x] __Wie speichern wir die Bilder ab.__
 Alternative 2 wird präferiert.

**Comment by KotschM** [comment]
Ich würde demnach auch zu Möglichkeit 2 tendieren.

**Comment by langmario** [comment]
Ich wäre auch für Möglichkeit 2, mit einem über ENV-Variablen/Konfigurationsdatei definierbaren Pfad, wo die Bilder abgespeichert werden sollen.
Dadurch lassen sich bei einer Containerisierung (etc.) der Anwendung Volumes zum persistieren anlegen.
