### ISSUE TITLE
F150, F170 Ressourcen hinzufügen

### ISSUE THREAD

**Issue by stolls** [MUDHub/MUDhub#40]
## Ziel des Features
Der Charakter soll Ressourcen verschiedener Art in sein Inventar aufnehmen können.
Die Ressourcen sollen aus dem Inventar heraus genutzt werden können. 
Die Nutzung der Ressourcen hat ggf. Einfluss auf die Statuswerte des Charakters.

## Technische Abhängigkeiten
- Änderungen an der Datenbank
- Änderungen am Server

## Statisches Modell
![Ressourcen](https://user-images.githubusercontent.com/52407490/79517194-c427c800-804d-11ea-8ba7-638c87959595.png)
- jeder Spieler besitzt ein `Inventar` (welches über eine festgelegte Kapazität verfügt)
- Ressourcen(`Items`) haben eine ID, Beschreibung, (Wert) und sind ggf. Waffe, Rüstung oder Consumable

## Offene Fragen
- [x] __Brauchen Quest-Items eine eigene Kind Klasse?__
 Nein
- [x] __Wie wird die Inventarkapazität realisiert? Gewicht oder Platz -> Darstellung__
 Gewicht-Option
- [x] __Können nicht-stackbare Items vom gleichen Charakter mehrfach aufgesammelt werden?__
 Alles ist unique. Einzige Begrenzung wäre das Gewicht.
- [x] __Soll auch jeder Raum ein Inventar besitzen, damit noch nicht aufgenommene Ressourcen dort hingelangen? (Siehe https://github.com/MUDHub/MUDhub/issues/40#issuecomment-615831663)__
 Jeder Raum und jeder Charackter besitzen ein Inventar.

**Comment by KotschM** [comment]
> Wie wird die Inventarkapazität realisiert? Gewicht oder Platz -> Darstellung

Ich würde die Inventarkapazität nach Anzahl der Plätze machen. Vergleichbar mit Minecraft.

**Comment by KotschM** [comment]
__Hinzufügen einer neuen noch offenen Frage.__
Eine Ressource kann einem Inventar zugeordnet werden. Jeder Charakter besitzt ein Inventar.
Meine Idee: Auch jeder Raum besitzt ein Inventar. Ressourcen, welche noch kein Charakter aufgenommen hat, sind dann in einem Inventar des Raumes.

**Comment by langmario** [comment]
> **Hinzufügen einer neuen noch offenen Frage.**
> Eine Ressource kann einem Inventar zugeordnet werden. Jeder Charakter besitzt ein Inventar.
> Meine Idee: Auch jeder Raum besitzt ein Inventar. Ressourcen, welche noch kein Charakter aufgenommen hat, sind dann in einem Inventar des Raumes.

Finde ich eine gute Idee, so lassen sich Gegenstände, die einfach "im Raum rumliegen" realisieren, die dann wiederrum mit "untersuche raum/boden/..." gefunden und aufgehoben werden können
