### ISSUE TITLE
BUG: Verfügbare MUDs anzeigen

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#88]
## Beschreibung des Bugs
Nach dem Einloggen wir bei der MUD-Übersicht und bei den eigens erstellten MUDs nichts angezeigt.

## Schritte zum reproduzieren:
1. Logge dich mit einem Account an.
2. Rufe die Seite "MUD-Übersicht" auf ODER die Seite "Meine MUDs"

## Zu erwartendes Verhalten
Es werden alle verfügbare MUDs angezeigt

## Tatäschliches Verhalten
Es werde keine MUDs angezeigt.
Erst wenn mann ein neues MUD anlegt, wird die Seite richtig mit Inhalt befüllt.

### Screenshots
=> Siehe Release V.01

## Benutzes Gerät:
- Chrome

**Weitere Informartionen**
- Vermutlich ein Bug beim Client

**Comment by langmario** [comment]
Fehler liegt im Server, beim anmelden wird in der UserApiModel.cs in Linie 33 eine NullPointerException geworfen
![image](https://user-images.githubusercontent.com/38465801/81000859-256dda80-8e47-11ea-9e49-d6e552738165.png)

**Comment by langmario** [comment]
Wurde gelöst durch ein include in der Datenbankabfrage
