### ISSUE TITLE
Bug: Anwendung ist noch nicht für Handys angepasst

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#92]
## Beschreibung des Bugs
Ruft man den Release V.0.1 auf einem Handy auf, so wird die Taskleiste NICHT Handyoptimiert angezeigt.

## Schritte zum reproduzieren:
Mit einem Handy die Website aufrufen.

## Zu erwartendes Verhalten
Taskleiste verschwindet in einem Icon. Durch Klicken des Icons kann man die einzelnen Tabs auswählen.

## Tatäschliches Verhalten
Die Beschriftungen der Tabs überlagern sich.

### Screenshots
![WhatsApp Image 2020-05-06 at 16 25 39](https://user-images.githubusercontent.com/48104013/81188997-53bdf800-8fb6-11ea-8e82-cb61f9df2399.jpeg)

## Benutzes Gerät:
 - Oneplus 6 (Chrome)

**Comment by langmario** [comment]
Bug ist bekannt, hat aber momentan keine Prio, da Handy-Optimierung nicht an vorderster Stelle steht

**Comment by langmario** [comment]
Und schließ mal ein paar Tabs...
