### ISSUE TITLE
Tech: Umsetzung des Default-Rooms

### ISSUE THREAD

**Issue by KotschM** [MUDHub/MUDhub#93]
## Feature Issues
- Konfigurieren des Muds

## Problemstellung
In welcher Form wird der Default-Room festgelegt?

## Bisherige Lösungen
- Ein Defaultraum kann NICHT gelöscht werden.
- Eine Area, welche einen Defaultraum enthält kann NICHT gelöscht werden.

## Mein Vorschlag
- Beim Konfigurieren des Muds muss man einen Raum auswählen, welcher als Defaultraum verwendet wird. Jeder Character startet in diesem Raum. Der Raum, welcher als Defaultraum ausgewählt wurde bleibt dies auch für immer. Ein Defaultraum kann nicht gelöscht werden.

- Wenn ein Character den Raum verliert, weil der Raum durch einen Mud Master gelöscht wurde, so springt der Character wieder zurück in den Defaultraum.

Das bedeutet. Damit ein Mud erfolgreich angelegt werden kann, muss mindestens eine Area mit einem Raum (=> Defaultraum) angelegt werden.

**Comment by langmario** [comment]
Ich würde beim Erstellen des Raumsystems einfach den MUD-Master festlegen lassen welche Area / welcher Raum der Default ist, über eine Checkbox / Liste / ...

Solange kein Default ausgewählt wurde lässt sich die Konfiguration des Raumsystems nicht abschließen

**Comment by KotschM** [comment]
Problematik wurde ausdiskutiert...
Bei Fragen einfach an @langmario  oder @KotschM wenden.
